- History https://www.youtube.com/watch?v=xGVRF-Y--hI
- https://www.youtube.com/watch?v=2BLRLuczykM
- https://www.youtube.com/watch?v=gk6NL1pZi1M
- Channel. https://www.youtube.com/@antirez/videos
- Channel: https://www.youtube.com/@Mr4thProgramming/videos
- Linux Programming with C by Nir Lichtman https://www.youtube.com/playlist?list=PL0tgH22U2S3Giz-yIxVQTEKIZpMBP0tMf
- Talks https://nullprogram.com/blog/2018/11/21/
- 90 [[https://archive.org/details/learning-c-programming-viagrafix-1990][Learning C Programming (Viagrafix, 1990)]]
- 08 Writing application fault handlers by Gilad Ben-Yossef https://bootlin.com/pub/video/2008/ols/ols2008-gilad-ben-yossef-fault-handlers.ogg
- 11 [[https://www.youtube.com/watch?v=BEQ3sRakIs0][Advanced C Coding For Fun!]] by Rusty Russell
- 14 [[https://vimeo.com/97505677][Insecure coding in C and C++]] by Olve Maudal
- 15 [[https://www.youtube.com/watch?v=eAhWIO1Ra6M][Advice for Writing Small Programs in C]] by Sean Barret
- 15 Hacking C for fun and Profit https://www.youtube.com/watch?v=bVxfwsgO00o
- 24 [[https://www.youtube.com/watch?v=RCPrPSowi0g][Normalization of the C programming language]] by Jens Gustedt

* Course: 6.S081: Learning by doing

Catalog description: Design and implementation of operating systems,
and their use as a foundation for systems programming. Topics include
virtual memory; file systems; threads; context switches; kernels;
interrupts; system calls; interprocess communication; coordination,
and interaction between software and hardware. A multi-processor
operating system for RISC-V, xv6, is used to illustrate these
topics. Individual laboratory assignments involve extending the xv6
operating system, for example to support sophisticated virtual memory
features and networking.

You may wonder why we are studying xv6, an operating system that
resembles Unix v6, instead of the latest and greatest version of
Linux, Windows, or BSD Unix. xv6 is big enough to illustrate the basic
design and implementation ideas in operating systems. On the other
hand, xv6 is far smaller than any modern production O/S, and
correspondingly easier to understand. xv6 has a structure similar to
many modern operating systems; once you've explored xv6 you will find
that much is familiar inside kernels such as Linux.
- https://www.youtube.com/playlist?list=PLTsf9UeqkReZHXWY9yJvTwLJWYYPcKEqK
- https://pdos.csail.mit.edu/6.S081/2021/schedule.html
- https://news.ycombinator.com/item?id=30094376

* 16 | How I program C                        | Eskil Steenberg
00:53:00
- video https://www.youtube.com/watch?v=443UNeGrFoM
- uses c89, c99 is too new and broken (fixed on c11)
- does NOT use: goto, register, do, continue, auto, volatile
- "ambiguity is the enemy"
  - in reference to
    - missmatched expectations between the code read and what the code does
    - having a programming language that does a thing in 2 lines of code
** Timestamps
 0:00  intro
5:00  garbage collection is not suitable for high performance scenarios
6:20  prefer stable & concise language features & technology stack
8:25  avoid ambiguity
11:00  don't be "clever"
11:45  be explicit
14:40  static-type language can catch more errors
16:00  early crashes are better than hidden bugs
17:30  improve your developing tools
20:20  general naming convention & coding style
27:20  prefer imperative & sequential code, long functions are OK
31:40  function naming
35:20  API design
36:00  how to organize .h & .c files
38:40  C & OOP-style APIs
41:00  void pointer is your friend to hide internal data
44:18  macros: _FILE__, __LINE_
49:40  a custom allocator for memory debugging
53:10  macro utilities for binary data packing/unpacking
57:10  memory control & pointers
1:03:00  malloc
1:06:00  arrays
1:09:20  struct
1:11:15  inheritance via C pointer casting
1:16:35  struct packing, padding, memory alignment
1:22:55  memory pages, realloc, gflags.exe
1:33:42  memory caches
1:42:30  don't store data twice
1:45:25  trick to reduce allocations: Flexible Array Member
1:48:30  trick to reduce allocations: joint malloc (dangerous)
1:50:48  use "stride" for better handling of Array Of Struct (AOS)
1:53:15  architecture on top of small & flexible primitives
1:55:45  prefer incremental progress
2:00:00  fix code ASAP
2:01:55  UI application design
2:08:50  Carmack's fast square root algorithm
2:09:56  magical random number generator
2:10:30  closing
** About C++

- it tries to be clever
- it tries to hide things, not explicit
- which is the root of all evil
- Examples:
  - ~operator overloading~
    - eg: on vector multiplication: is it dot product or pairwise multiplication?
    - where i could have used =vector_dot()= and =vector_mul()=
  - ~overloading~
    - eg: what happens when on an add(X,Y) defined on same types. I mix different types?
    - where I could have used =addf()=, (ME: like in ocaml)
  - ~on js: undefined field on an object~ the compiler won't complain, it will just return undefined(?)

** long functions are good
- have more code that "does something"
- instead of code that handles code
** a swedish fighter jet's code has only 1 main(), that calls functions and those functions NEVER call anything else
  - reduces indirection
** naming

- Have long names, wide code is better, more descriptive
- _use words that complement each other_: create/destroy, load,unload
- eg:
  - object_action()
  - module_object_action()
- files
  - s_draw_font.c
  - s_draw_internal.h
  - s_widget_buttons.c
  - s_widgtet_sliders.c
  - seduce.h

*** words used for naming things

- handle, pointer to opaqe data structure
- func, funtion pointer OR function used as function pointer
- internal, function internal to a module

** OO in C

- other languages try to fool that it is something that has both code and data in it
  which is not true on modern systems (aka separate memory spaces)
- object_create()
  object_do_something()
- void pointers are your friend
  - helps creating opaqe types on interfaces (.h) for users of libraries
  - on the public .h
    #+begin_src c
      typedef void RShader
    #+end_src
  - on the internal .h
    #+begin_src c
      typedef struct {
        // ...
      } RShader;
    #+end_src

** Macros 00:50:00
- Doesn't like them
- One reason to use them is to duplicate A LOT of code for different types
  - still screws the error messages
- To create debug logging macros.
  You can register file/line and create counters for it.
  for malloc() realloc() free()
  #define malloc(n) f_debug_mem_malloc(n, __FILE__, __LINE__)
* DONE 19 |"New" Features in C                     | Daniel Saks
https://www.youtube.com/watch?v=ieERUEhs910
- C++ dev, working also on C
- Reserved identifiers
  - for global scope, those starting with undersore
  - for all, starting with 2 underscores, or underscore and uppercase
- C90 _STDC_ is "1" if fully implements "Standard C"
- C99 _STDC_VERSION_ to which version of the standard is used
  - 201710L for C18
  - 201112L for C11
  - 199901L for C99
  -      1  for C90
* TODO 21 | Modern C and What We Can Learn From It | Luca Sas

- 39:00
- https://www.youtube.com/watch?v=QpAhX-gsHMs
- WG14 Standarization Group https://www.open-std.org/jtc1/sc22/wg14/
- instead of using malloc/fopen, ask for allocators iocallbacks, or buffers from the user
- centralization of resource managment (custom allocators, system-wide resource managers)
- macro: to differentiate between c++ and c
  #+begin_src c
    #ifdef __cplusplus
    #endif
  #+end_src
- C11
  - atomics (replaces C89atomics)
  - thread_local (replaces C99 compiler extensions)
  - static_assert()
  - =_Generic= and Overloading
    #+begin_src c
      #define min(a,b) _Generic((a), float: minf(a,b), int: mini(a,b))
    #+end_src

- macro: Dynamic array
  - stb_ds.h

** Example: using sokol gfx, we describe a pipeline, we initialize the others to 0/default
#+begin_src c
  sg_pipeline_desc pip_desc = {
    .layout = {
      .buffers[0].stride = 28,
      .attrs = {
        [ATTR_vs_position].format = SG_VERTEXFORMAT_FLOAT3,
        [ATTR_vs_color0].format   = SG_VERTEXFORMAT_FLOAT4
      }
    },
    .shared = shd,
    .index_type = SG_INDEXTYPE_UINT16,
    .depth_stencil = {
      .depth_compare_func = SG_COMPAREFUNC_LESS_EQUAL,
      .depth_write_enagled = true,
    }
    .rasterizer.cull_mode = SG_CULLMODE_BACK,
    .rasterizer.sample_count = SAMPLE_COUNT,
    .label = "cube-pipeline"
  };
#+end_src

** macro: defer-like, begin-end

#+begin_src c
  #define macro_var(name) concat(name, __LINE__)
  #define defer(start,end) for (     \
     int macro_var(_i_) = (start,0); \
     !macro_var(_i_);                \
     (macro_var(_i_) += 1), end)

  #define profile defer(profile_begin(), profile_end())
  profile
  {
   ...
  }

  #define gui defer(gui_begin(),gui_end()
  gui
  {
    ...
  }
#+end_src

** macro: defer-like, scope
#+begin_src c
  file_handle_t file = file_open(filename, file_mode_read);
  scope(file_close(file))
  {
    ...
  }
#+end_src

** API Design

- Value Oriented Design: https://youtu.be/QpAhX-gsHMs?t=1227
  - passing arguments by values is prefered in "Modern C"

*** Error Handling

- traditionally checking return codes one by one
- or with a *goto*
- NEW: return a struct with a *valid* field
  #+begin_src c
    typedef struct file_contents_t {
      char *data;
      isize_t size;
      valid_t valid; // <----- aka a "bool"
      error_code_t valid; // <----- enum?
    } file_contents_t;
  #+end_src

- It "chains" well (similar-ish to Optional for valid, or Result for error_code)
  #+begin_src c
    file_contents_t fc = read_file_contents("milo.cat");
    image_t img = load_image_from_file_contents(fc);
    texture_t texture = load_texture_from_image(img);
    if (texture.valid) {
    }
  #+end_src

*** Unions: We can refer to the same thing in different ways

#+CAPTION: example from "Hand Made Math" library
#+begin_src c
  typedef union hmm_vec2 {
    struct { float X, Y; };
    struct { float U, V; };
    struct { float Left, Right; };
    struct { float Width, Height; };
    float Elements[2];
  } hmm_vec2;
#+end_src

* DONE 23 | Programming in Modern C                | Dawid Zalewski

- 01:14:00
- https://www.youtube.com/watch?v=lLv1s7rKeCM
- most things default to *int*
- struct definitions can be on the return type of a function directly
- typeof()
- *auto* for storage duration specification and (in C23) for type inference
- 23 -std=C2X
  - constexpr
  - bool (without include)
  - nullptr
- zeroing, assigning, ephemeral lvalues
  - Compound Literals

** Example

#+begin_src c
  struct Rect{ struct {long n;}; } will_it_run(bool yes_or_no) {
    typeof(yes_or_no) should_segfault = { !yes_or_no };
    constexpr int SZ = {6};
    double array[SZ] = {
      [4] = 2.3, 3.2,
      [0] = 3.1, 4.2
    };
    auto num = puts((void*)(array));
    auto ptr = &(struct Rect){ .n = num };
    if (should_segfault)
      ptr = nullptr;
    return *ptr
  }

  int main(void) {
    return will_it_run(true).n;
  }
#+end_src
** initialization
  - { } for struct, array, for floats(?
  - {0} Empty Initialization, zero outs (on C23 you don't need the 0)
  - { .foo = 0 } Designated Initializers
    - =zero outs fields not explicitly initialized=
    - can be mixed with positional ones (ME: ugh!)
    - can be nested, even with multiple dots (!)
  - { [1] = 0 } Designated Initializers for subscripts
    - rest zero'd
** pointers, arrays, functions
- use VLA style for function array arguments
  #+begin_src c
  void g(size_t n, int numbers[n]) {} // for unintialized arrays
  void g(size_t n, int numbers[static n]) {} // for valid arrays
  #+end_src
** Macro Magic: Designated initiliazers as keyword arguments

  #+begin_src c
    image_s *blur_(image_s img[static 1], blur_params_s params[static 1]);
    // Macro to make it's usage more like "keyword arguments"
    #define blur(img, ...) blur_((img), &(blur_params_s){__VA_ARGS__})
    // Macro with custom default values...with warnings...
    #define blur(img, ...) blur_((img), &(blur_params_s){.width=32,__VA_ARGS__})
    blur(&img, .width=64, .in_place=true)
  #+end_src

** Fragile Resource Managment:

  You cannot longer: make an array of this, be a member of other struct, direct init.
  You can skip a malloc. And do it in 1(one) go. Ensuring contiguous memory.
  #+begin_src c
    typedef struct string {
      size_t sz_arr;
      size_t length;
      char arr[]; // <--- flexible array member, must be at the END
    } string_s;
  #+end_src

** Macro Magic: _Generic (C11)
#+begin_src c
  #define scale(obj, scale)             \
    _Generic((obj),                     \
             Rectangle_s* : scale_rect, \
             Circle_s*    : scale_circ  \
             )                          \
    ((obj),(scale))
#+end_src

** Macro Magic: Variadic Overload

#+begin_src c
  #define scale2p(obj, ...)        \
    _Generic( (obj),               \
      Rectangle_s* : scale_rect_2p \
      )((obj), __VA_ARGS__)
#+end_src

* 24 | Tips for C Programming                 | Nic Barker
https://www.youtube.com/watch?v=9UIIMBqq1D4

* Tsoding
- 17 tic-tac toe https://www.youtube.com/watch?v=gCVMkKgs3uQ
- Genetic Programming https://www.youtube.com/playlist?list=PLpM-Dvs8t0VZhPhStYD0aS30Y1awAv-DO
- Lisp in C https://www.youtube.com/playlist?list=PLpM-Dvs8t0VYbTFO5tBwxG4Q20BJuqXD_
- Virtual Machine in C https://www.youtube.com/playlist?list=PLpM-Dvs8t0VY73ytTCQqgvgCWttV3m8LM
- Build System in C https://www.youtube.com/playlist?list=PLpM-Dvs8t0VZpih2sTx6povEocoKEUBnk
- Cellular Automata https://www.youtube.com/playlist?list=PLpM-Dvs8t0VYX7q4RQsx6mOSWFDzvvnxg
- GC in C https://www.youtube.com/playlist?list=PLpM-Dvs8t0VYuYxRxjfnkdHvosHH8faqc
- Mini Excel in C https://www.youtube.com/playlist?list=PLpM-Dvs8t0VYfQc5dq21Vc81G1rGHwkmT
** 21 | Searching duplicate files with C
00:53:00
https://www.youtube.com/watch?v=bpCJf67e1lI
- Task: Hashing each file
- you can use "(void) varname" to silence warning of unused variable.
- #include <dirent.h>
  - =opendir()=
  - =readdir()= - returns the next entry within the directory
  - =closedir()=
- unix filenames can only be upto 256
- we ignore "." and ".."
  if ((strcmp(ent->d_name, ".") != 0) && strcmp(ent->d_name, "..") != 0)
- string literals are null terminated
  #+begin_src c
    #define PATH_SEP "/" // string literals come with the null termitor character
    #define PATH_SEP_LEN (sizeof(PATH_SEP) - 1)
  #+end_src
- join_path function, a very c way to append strings with =malloc/memcpy= and pointer adding
  #+begin_src c
    char *join_path(const char *base, const char *file) {
      size_t base_len = strlen(base);
      size_t file_len = strlen(file);

      char *begin = malloc(base_len + file_len + PATH_SEP_LEN + 1);
      assert(begin != NULL);

      char *end = begin;
      memcpy(end, base, base_len);
      end += base_len;
      memcpy(end, PATH_SEP, PATH_SEP_LEN);
      end += PATH_SEP_LEN;
      memcpy(end, file, file_len);
      end += file_len;
      *end = '\0';

      return begin;
    }
  #+end_src
- to be able to perform an action on each file, WITHOUT interacting with the recursion of readdir()
  we creates a wrapper API struct that keep an array of DIR* around
** 21 | Checking out raylib

https://www.youtube.com/watch?v=fHojJ9Nxb0E

 03:22:00 START

- is like an engine as a library
- a zero initialized structure, is a convention that should be handled
  by the functions handling them
  = {0}

*** Example: minimal example

#+begin_src c
  #include "raylib.h"
  #define SCREEN_WIDTH 800
  #define SCREEN_HEIGHT 600
  int main(void) {
    InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "raylib probe");
    while (!WindowShouldClose()) {
      BeginDrawing();
      CLearBackground(BLACK);
      EndDrawing();
    }
    return 0;
  }
#+end_src

** 21 | Using C instead of Bash
- for(; *argv != NULL; argv++) can have a missing initialization parameter
*** shlex
- Python Package https://docs.python.org/3/library/shlex.html
  - *shlex.quote*, escapes a string to be parsed by a command
- strchr()
  - locates a character in string
- We do string concatenation by
  - doing a single memory allocation of an array of charj
  - and providing an API to memcpy into it cstrings
** 21 | Minicel
*** TODO 1 https://www.youtube.com/watch?v=HCAgvKQDJng
01:26:00
- uses ~size_t~ for anything related to array indices
- Implementation of C++'s StringView in C https://github.com/tsoding/sv
- using =goto= to return an error, a way to imitate part of Go's "defer"
  #+begin_src c
    char* slurp_file(const char *file_path, size_t *size) {
      FILE *f = fopen(file_path, "rb");
      char *buffer = NULL;
      if (f == NULL) goto error;
      if (fseek(f, 0, SEEK_END) < 0) goto error;

      long m = ftell(f);
      if (m < 0) goto error;

      buffer = malloc((sizeof char) * m);
      if (buffer == NULL) goto error;

      if (fseek(f, 0, SEEK_SET) < 0) goto error;
      size_t n = fread(buffer, 1, m, f);
      assert(n == (size_t) m);

      if (ferror(f)) goto error;
      if (size) *size = n;
      fclose(f);

      return buffer;

     error:
      if (f)      fclose(f);
      if (buffer) free(buffer);
      return NULL;
    }
  #+end_src
- reading a whole file into a string
  - stat() is not windows portable
  - ftell - to take the value of the cursor
    fseek - to put the cursor to the end of the file
- suffixing ~union~ with _As, AND naming the structure field ~as~, makes it so code will look like this
  #+begin_src c
  Cell.as.text;
  Cell.as.number;
  Cell.as.expr;
  #+end_src
- When creating unions, make sure that a ~zero initialization~ ({0} or memset()) still gives a valid results for all cases
- using *unions*, *enums* and *structs* together
  #+begin_src c
    typedef enum {
      CELL_KIND_TEXT = 0,
      CELL_KIND_NUMBER,
      CELL_KIND_EXPR,
    } Cell_Kind;

    typedef union {
      String_View text;
      double number;
      Expr expr;
    } Cell_As;

    typedef struct {
      Cell_Kind kind;
      Cell_As as;
    } Cell;
  #+end_src
- using *macros* to unpack, a hex color (#0xFFAABBCC) into 4 arguments
  #+begin_src c
    #define UNHEX(c) \
      ((c >> 8 * 0) & 0xFF), \
      ((c >> 8 * 1) & 0xFF), \
      ((c >> 8 * 2) & 0xFF), \
      ((c >> 8 * 3) & 0xFF), \
  #+end_src
- using *macros* to format
  #+begin_src c
    typedef struct {
      int x, y;
    } Vec2;

    #define V2_Fmt "(%d, %d)"
    #define V2_Arg(v) v.x, v.y
  #+end_src
- strtod() - string to double
  strtof() - string to float
